### ISSUE TITLE
Firestore structure implemented

### ISSUE THREAD

**Issue by mattmaloof** [Adam-Henrie/LiveCourier-UT3#16]
Implemented Firestore for item and store information / data.

**Comment by Adam-Henrie** [comment]
Current sections of the Firestore Structure that are now set up: 
The cart
The info for the item details page
The store information includes a tree to all of the inventory info. 
User profile information as well as location data]

* Things that still need to be implemented over time in Firestore
Non-local location data for every store so that closest store calculations can be done
Order information section
Order tracking section
Item Inventory amount update functions that access current inventory.
*Edit update:
also user account funds

*most likely during third sprint
Driver information
